# 빌드를 위한 스테이지
FROM golang:1.19 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-gs-ping

# distroless 이미지를 활용한 스테이지
# FROM gcr.io/distroless/base-debian11 AS build-release-stage
FROM gcr.io/distroless/base-debian11:debug AS build-release-stage

WORKDIR /

COPY --from=build-stage /docker-gs-ping /docker-gs-ping

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/docker-gs-ping"]